envVarGroups:
  - name: repro-secrets
    envVars:
      - key: MY_SECRET_PATH
        value: /etc/secrets/my_secret.json

services:
  - type: worker
    runtime: python
    name: secret-file-repro
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.12"
      - fromGroup: repro-secrets
