services:
  - type: worker
    runtime: python
    name: secret-file-repro
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.12"
      - key: MY_SECRET_PATH
        value: /etc/secrets/my_secret.json
    secretFiles:
      - name: my_secret.json
        contents: '{"secret_key": "hello_world"}'
